### ISSUE TITLE
v1 TODO

### ISSUE THREAD

**Issue by michelson** [rauversion/rauversion-phx#55]
### TODO
- [x] User account
- [x] File uploads Avatar
- [x] User auth
- [x] Tracks
- [x] Add metadata form step
- [x] Embed at /embed/:track_id
- [x] Embed at /embed/:track_id/private with signed_id
- [x] Filter public/private tracks (where: private: true)
- [x] Reposts
- [x] Likes
- [x] Private preview on show
- [x] Followers / Followings
- [x] load waveform data as data
- [x] Range responses
- [x] Fix specs on tests/rauversion
- [x] Paginate profile tracks /:username
- [x] Paginate /tracks
- [x] Centralized player, fixed (bottom) across navigation
- [x] Make GithubActions work!
- [x] Refactor audio processing, add proceesing queue for the after upload
- [x] Telemetry for dashboard/ metrics / insights
- [x] A logo for rauversion
- [ ] A WYSIWYG editor for Markdown for Track/Playlist description
  - [x] fallback to a formatted plain text with auto link
- [ ] Playlists
  - [x] add to playlist select playlist / modal first tab
  - [ ] sort songs on playlist
  - [ ] like button playlist/show
  - [ ] share button playlist/show
  - [x] playlist player
- [ ] Fix specs on tests/rauversion-web
- [ ] Listening history
- [ ] Give feedback on upload preprosessing
- [ ] Albums
